name: Actions Workflow
on: pull_request

# on:
#   push:    
#     branches:
#       - master
#       - 'feature/*' # matches feature/featA, feature/featB # doesn't match feature/feat/a
#       - 'feature/**' ## matches any string
#       - '!feature/featC' # ignore this branch - should be put after the patterns
#     # branches-ignore: ## to ignore some branches ## is not possible to use branches and branches-ignore
#     # - hotfix
#     tags:
#       - "v1.*"
#     # tags-ignore: # the same case of branches/branches-ignore
#     paths:
#       - '**.js' # any change in .js scripts will trigger the workflow
#       - '!filename.js' # runs for all java scripts, execept for this filename.js
#     # paths-ignore: # the same case of branches-ignore/tags-ignore
#     # - 'docs/**'    

#   # repository_dispatch:
#   #   types: [build]
#   ## executar workflow apartir de eventos externos, exemplo POSTMAN > https://api.github.com/repos/7700472077/github-actions-test/dispatches  
  
#   # schedule:
#   #   - cron: "0/5 * * * *" # a cada 5 minutos | eh o minimo permitido
  
#   # push:
#   # pull_request:
#   #   types: [closed, assigned, opened, reopened]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Payload
        run: echo ${{ github.event.client_payload.env }}

      - name: List Files
        run: |
          pwd
          ls -lhart
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo ${{ github.token }}

      - name: Checkout Github Project
        uses: actions/checkout@v3

      - name: List Files Again
        run: |
          pwd
          ls -lhart

      - name: Simples JS Actions
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Leonardo Sete

      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"