name: Matrix
on: push
jobs:
  example-matrix:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest] ## vai rodar 2 x por conta do array
        node_version: [6, 8, 10] ## como existe +3 valores, ele vai rodar 6x = 2x3
      # fail-fast: true ## se uma execução do job falhar, vai parar tudo
      # max-parallel: 3 ## default eh rodar tudo em paralelo
    runs-on: ${{ matrix.os }}
    steps:
      - name: Log node version
        run: node -v
      
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      
      - name: Log node version
        run: |
          node -v