name: Matrix
on: push
jobs:
  example-matrix:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest] ## vai rodar 3 x por conta do array
        node_version: [6, 8, 10] ## como existe +3 valores, ele vai rodar 9x = 3x3
        include:
          - os: ubuntu-latest
            node_version: 8
            is_node_8: "true" ## variável foi criada ao rodar no ubuntu-latest + node_version 8
          - os: windows-latest
            node_version: 10
            is_node_10: "true"
        exclude:
          - os: ubuntu-latest ## nao vai rodar no ubuntu-latest com node_version 6
            node_version: 6
          - os: macos-latest ## nao vai rodar no macos-latest com node_version 8
            node_version: 8
      # fail-fast: true ## se uma execução do job falhar, vai parar tudo
      # max-parallel: 3 ## default eh rodar tudo em paralelo
    runs-on: ${{ matrix.os }}
    env: 
      IS_NODE_8: ${{ matrix.is_node_8 }}
      IS_NODE_10: ${{ matrix.is_node_10 }}
    steps:
      - name: Log node version
        run: node -v
      
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      
      - name: Log node version
        run: |
          node -v
          echo $IS_NODE_8
          echo $IS_NODE_10
