name: Shell Commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "teste sete"
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: Python command
        shell: python
        run: |
          import platform
          print(platform.processor())

  run-windows-command:
    runs-on: windows-latest
    steps:
      - name: Directory powershell
        shell: powershell
        run: Get-Location
      - name: Directory Bash
        shell: bash
        run: pwd
