name: Shell Commands

on:
  # schedule:
  #   - cron: "0/5 * * * *" # a cada 5 minutos
  push:
  # pull_request:
  #   types: [closed, assigned, opened, reopened]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Teste Sete"
        continue-on-error: true ## vai continuar mesmo se um step falhar

      - name: multiline script
        run: |
          node -v
          npm -v
          eccho "nada"
          
      - name: Python command
        shell: python
        run: |
          import platform
          print(platform.processor())

  run-windows-command:
    runs-on: windows-latest
    needs: ["run-shell-command"]
    steps:
      - name: Directory powershell
        shell: powershell
        run: Get-Location

      - name: Directory Bash
        shell: bash
        run: pwd