name: Shell Commands

on: pull_request
  # schedule:
  #   - cron: "0/5 * * * *" # a cada 5 minutos
  # push:
  # pull_request:
  #   types: [closed, assigned, opened, reopened]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: echo a string
        run: eccho "Teste Sete"
        continue-on-error: true ## vai continuar mesmo se o step anterior falhar

      - name: multiline script
        run: |
          node -v
          npm -v

      - name: Python command
        shell: python
        run: |
          import platform
          print(platform.processor())

  run-windows-command:
    runs-on: windows-latest
    needs: ["run-shell-command"]
    steps:
      - name: Directory powershell
        shell: powershell
        run: Get-Location

      - name: Directory Bash
        shell: bash
        run: pwd